### ISSUE TITLE
Draw/Sketch Event form submission page

### ISSUE THREAD

**Issue by itpwang** [480Random5/event-codex#3]

**Comment by vanile** [comment]
![Event Submission Form Sketch.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59de728d9b7ab80011d3ea67/125516c66e82c728ace21e0d46cd829f2d96c39a9aebb24ab74ef99b2706017c3b09e3187b80f72bb70037431f1d11f6140b1b56f6eb8c22f2e33a26d95c08ea85690c21c63d19a5b9864ceb01e832975dc7e7e2de139db17770a599855d3f170f198cff5a3ca2904dce59ff4ee65f18.png)

Not supposed to take whole page, even though it looks like it does. DateSelector is a drop down calendar widget that allows user to select date. Also the time selector is a drop down with a similar functionality
